### PR TITLE
Support partition compaction key

### LINKED ISSUE #125: Support log compaction
There is additional meta data needed for this new feature.

### PR DESCRIPTION
**Pull request by rbobin**
Closes #125

### CODE REVIEW

**Comment by mtesseract** [comment]
Hi, thanks!  Right now I cannot give an appropriate review for this. But from first glance the code looks good. I am not familiar with this new feature.  But since there is additional review let's merge this. Can you add a version bump please? Thanks!

**Comment by rbobin** [comment]
@mtesseract sure thing, I will add it. You can find more info about this feature [here](https://nakadi.io/manual.html#definition_EventMetadata*partition_compaction_key)

**Comment by mtesseract** [comment]
Thanks. Should we also add support for this cleanup_policy field then?

**Comment by rbobin** [comment]
Good idea :)

**Comment by mtesseract** [comment]
As part of this pr or separately? Feel free to choose.

**Pull request merged**
